---
title: "Observation analysis"
author: "Bastien BENNETOT"
date: "11 mai 2017"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE, message=FALSE)
```

#Inititalisation
```{r}
setwd("~/Bureau/STAGE M1 IMPORTANT/algo")
library(dplyr)
library(ggplot2)
library(ggmap)
require(plyr)
require(reshape2)
library(Hmisc)
`%ni%` <- Negate(`%in%`) 
#Load of dataframe
amanita_species_name<-read.table(file = "amanita_species_name.csv",sep=",")
colnames(amanita_species_name)<-"specname"

gbif_amanita<-read.csv(file = "gbif_amanita.csv")


#mushroom_observer_all<-read.csv(file = "mushroom_observer_all.csv")
#mushroom_observer_all_usa<-read.csv(file = "mushroom_observer_all_usa.csv")
mushroom_observer_amanita<-read.csv(file = "mushroom_observer_amanita.csv")
mushroom_observer_amanita_usa<-read.csv(file = "mushroom_observer_amanita_usa.csv")

#inaturalist_all<-read.csv(file = "inaturalist_all.csv")
#inaturalist_all_usa<-read.csv(file = "inaturalist_all_usa.csv")
inaturalist_amanita<-read.csv(file = "inaturalist_amanita.csv")
inaturalist_amanita_usa<-read.csv(file = "inaturalist_amanita_usa.csv")

#Attribute same (amanita) specname function
amanita_specname<-function(dataset,amanita_species_name){
  #in case that there is "sect." between "amanita"" and the species name
  levels(dataset$specname)<-gsub(pattern=" sect.","" ,x=levels(dataset$specname))
  #Change species names following the pattern "Amanita name"
  for (i in amanita_species_name$specname)
  {
    
   levels(dataset$specname)[grep(pattern = i,levels(dataset$specname),ignore.case = TRUE)]<-rep(i,each=length( levels(dataset$specname)[grep(pattern = i,levels(dataset$specname),ignore.case = TRUE)]))
  }
dataset<-dataset[dataset$specname%in%amanita_species_name$specname,]
dataset<-droplevels(dataset)  
return(dataset)
}

mushroom_observer_amanita<-amanita_specname(mushroom_observer_amanita,amanita_species_name)
mushroom_observer_amanita_usa<-amanita_specname(mushroom_observer_amanita_usa,amanita_species_name)
inaturalist_amanita<-amanita_specname(inaturalist_amanita,amanita_species_name)
inaturalist_amanita_usa<-amanita_specname(inaturalist_amanita_usa,amanita_species_name)
gbif_amanita<-amanita_specname(gbif_amanita,amanita_species_name)



#Reduction to America function
reduction_to_usa <-function(dataset){
dataset<-dataset[dataset$latitude>25,]
dataset<-dataset[dataset$latitude<50,]
dataset<-dataset[dataset$longitude< -67,]
dataset<-dataset[dataset$longitude> -130,]
dataset<-droplevels(dataset)
return(dataset)
}



gbif_amanita_usa<-reduction_to_usa(gbif_amanita)

#Mixed dataset
gbif_amanita$observation <- seq.int(nrow(gbif_amanita))
mushroom_observer_amanita<-mushroom_observer_amanita[,c("observation","latitude","longitude","specname")]
inaturalist_amanita<-inaturalist_amanita[,c("observation","latitude","longitude","specname")]
gbif_amanita<-gbif_amanita[,c("observation","latitude","longitude","specname")]
mixed_amanita<- rbind(gbif_amanita,mushroom_observer_amanita)
mixed_amanita$observation <- seq.int(nrow(mixed_amanita))
mixed_amanita_usa<-reduction_to_usa(mixed_amanita)


#Plot observation map for each species function
plot_observation_map<-function(dataset,name_of_the_dataset,location){
  
print(qplot(summary(dataset$specname), geom="histogram",binwidth=5,main=paste("Number of observation per species for",name_of_the_dataset), xlab = "Observations", ylab = "Species",alpha=I(0.8),fill=I("red"),col=I("white")))
 name_of_the_dataset<- capitalize(name_of_the_dataset)

mp <- NULL
mapWorld <- borders(location, colour="grey50", fill="grey50" ) # create a layer of borders
mp <- ggplot() +   mapWorld + ggtitle(name_of_the_dataset)+xlab("Longitude")+ylab("Latitude")+  theme(plot.title = element_text(hjust = 0.5))
mp <- mp + geom_density2d(data=dataset, aes(x = longitude, y= latitude),size=0.05,col="black")+ stat_density2d(data =dataset, aes(x = longitude, y= latitude,fill = ..level.., alpha = ..level..), geom = 'polygon')+scale_fill_gradient(low = "green", high = "red")+scale_alpha(range = c(0.25, 0.85), guide = FALSE,limits=c(0,1))
mp <- mp+ geom_point(data=dataset, aes(x = longitude, y= latitude), size=0.01,pch=20,color="black") 
mp <- mp+ geom_rug(data=dataset, aes(x = longitude, y= latitude), size=0.1,pch=20,color="red") 
plot(mp)  
}

```

#All amanita from mushroom observer
```{r}
plot_observation_map(mushroom_observer_amanita,"all amanita from mushroom observer","world")
``` 

#All amanita from mushroom observer in the usa
```{r}
plot_observation_map(mushroom_observer_amanita_usa,"all amanita from mushroom observer in the usa","usa")
``` 

#All amanita from iNaturalist
```{r}
plot_observation_map(inaturalist_amanita,"all amanita from iNaturalist","world")
``` 

#All amanita from iNaturalist in the usa
```{r}
plot_observation_map(inaturalist_amanita_usa,"all amanita from iNaturalist in the usa","usa")
``` 

#All amanita from gbif
```{r}
plot_observation_map(gbif_amanita,"all amanita from gbif","world")
```

#All amanita from gbif in the USA
```{r}
plot_observation_map(gbif_amanita_usa,"all amanita from gbif","world")
```

#All amanita from all data
```{r}
plot_observation_map(mixed_amanita,"all amanita from mixed data","world")
``` 



#All amanita from all data in the usa
```{r}
plot_observation_map(mixed_amanita_usa,"all amanita from mixed data in the usa","usa")
``` 





